================================================================================
-- SCRIPT MAESTRO COMPLETO - SISTEMA BANCARIO ORACLE XE
-- Fecha: 1 de junio de 2026
-- Incluye: DDL, Paquetes, Triggers, Índices, Datos de Prueba
-- Ejecución: Soporta Oracle XE 21c
================================================================================

SET ECHO OFF
SET FEEDBACK OFF
WHENEVER SQLERROR CONTINUE

-- ============================================================
-- PARTE 1: LIMPIAR BASE DE DATOS (DROP IF EXISTS)
-- ============================================================

BEGIN
  FOR cur IN (SELECT table_name FROM user_tables 
    WHERE table_name IN ('TRANSACCION','TARJETA_DEBITO','TARJETA_CREDITO','TARJETA',
                        'CUOTA','ABONO_EXTRAORDINARIO','PRESTAMO','CUENTA',
                        'CAJERO','CLIENTE','SUCURSAL','ADMINISTRADOR','AUDITORIA_CAMBIOS'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||cur.table_name;
  END LOOP;
END;
/

BEGIN
  FOR cur IN (SELECT sequence_name FROM user_sequences 
    WHERE sequence_name IN ('SEQ_ADMINISTRADOR','SEQ_CAJERO','SEQ_CUENTA','SEQ_PRESTAMO',
                           'SEQ_CUOTA','SEQ_TARJETA','SEQ_TRANSACCION','SEQ_SUCURSAL',
                           'SEQ_ABONO','SEQ_AUDITORIA'))
  LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE '||cur.sequence_name;
  END LOOP;
END;
/

BEGIN
  FOR cur IN (SELECT package_name FROM user_packages 
    WHERE package_name IN ('PKG_ADMINISTRADOR','PKG_CLIENTES','PKG_CUENTA','PKG_SUCURSAL',
                          'PKGC_ABONOS','PKGC_CAJEROS','PKGC_CUOTAS','PKGC_PRESTAMOS',
                          'PKGC_TARJETAS','PKGC_TRANSACCIONES'))
  LOOP
    EXECUTE IMMEDIATE 'DROP PACKAGE '||cur.package_name;
  END LOOP;
END;
/

PROMPT ============================================================
PROMPT LIMPIEZA COMPLETADA
PROMPT ============================================================

-- ============================================================
-- PARTE 2: CREAR SECUENCIAS (10 secuencias)
-- ============================================================

CREATE SEQUENCE SEQ_ADMINISTRADOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CAJERO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CUENTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRESTAMO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CUOTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TARJETA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRANSACCION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SUCURSAL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ABONO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

PROMPT Secuencias creadas exitosamente

-- ============================================================
-- PARTE 3: CREAR TABLAS (11 tablas con constraints)
-- ============================================================

CREATE TABLE ADMINISTRADOR (
    ID_ADMINISTRADOR NUMBER(12,0) PRIMARY KEY,
    FECHA_ASIGNACION_ADMINISTRADOR TIMESTAMP DEFAULT SYSTIMESTAMP,
    EMAIL_ADMINISTRADOR VARCHAR2(120 BYTE) UNIQUE NOT NULL,
    CONTRASENA_ADMINISTRADOR VARCHAR2(50 BYTE) NOT NULL
);

CREATE TABLE SUCURSAL (
    ID_SUCURSAL NUMBER(12,0) PRIMARY KEY,
    NOMBRE_SUCURSAL VARCHAR2(120 BYTE) NOT NULL,
    DIRECCION_SUCURSAL VARCHAR2(200 BYTE),
    TELEFONO_SUCURSAL VARCHAR2(30 BYTE),
    ESTADO_SUCURSAL VARCHAR2(10 BYTE) DEFAULT 'abierta' CHECK (ESTADO_SUCURSAL IN ('abierta','cerrada')),
    ID_ADMINISTRADOR NUMBER(12,0) REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE VARCHAR2(10 BYTE) PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR2(120 BYTE) NOT NULL,
    EMAIL_CLIENTE VARCHAR2(120 BYTE) UNIQUE NOT NULL,
    TELEFONO_CLIENTE VARCHAR2(30 BYTE),
    ESTADO_CLIENTE VARCHAR2(10 BYTE) DEFAULT 'ACTIVO' CHECK (ESTADO_CLIENTE IN ('ACTIVO','INACTIVO')),
    FECHA_REGISTRO_CLIENTE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CEDULA_CLIENTE NUMBER(12,0) UNIQUE NOT NULL
);

CREATE TABLE CUENTA (
    ID_CUENTA NUMBER(12,0) PRIMARY KEY,
    ID_CLIENTE VARCHAR2(10 BYTE) NOT NULL REFERENCES CLIENTE(ID_CLIENTE),
    ID_ADMINISTRADOR NUMBER(12,0) NOT NULL REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR),
    SALDO_CUENTA NUMBER(15,2) DEFAULT 0 CHECK (SALDO_CUENTA >= 0),
    FECHA_CREACION_CUENTA TIMESTAMP DEFAULT SYSTIMESTAMP,
    ESTADO_CUENTA VARCHAR2(10 BYTE) DEFAULT 'activa' CHECK (ESTADO_CUENTA IN ('activa','inactiva')),
    FECHA_ULTIMA_TRANSACCION_CUENTA TIMESTAMP,
    CONTRASENA_CUENTA VARCHAR2(30 BYTE)
);

CREATE TABLE PRESTAMO (
    ID_PRESTAMO NUMBER(12,0) PRIMARY KEY,
    ID_SUCURSAL NUMBER(12,0) REFERENCES SUCURSAL(ID_SUCURSAL),
    MONTO_PRESTAMO NUMBER(15,2) NOT NULL CHECK (MONTO_PRESTAMO > 0),
    TASA_DE_INTERES_PRESTAMO NUMBER(5,2) DEFAULT 0,
    PLAZO_PRESTAMO NUMBER(6,0) DEFAULT 0,
    FECHA_INICIO_PRESTAMO TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_VENCIMIENTO_PRESTAMO TIMESTAMP,
    ESTADO_PRESTAMO VARCHAR2(12 BYTE) CHECK (ESTADO_PRESTAMO IN ('solicitado','activo','rechazado','pagado')),
    FECHA_ULTIMO_PAGO_PRESTAMO TIMESTAMP,
    SALDO_PRESTAMO NUMBER(15,2) DEFAULT 0 CHECK (SALDO_PRESTAMO >= 0),
    ID_CUENTA NUMBER(12,0) REFERENCES CUENTA(ID_CUENTA)
);

CREATE TABLE CUOTA (
    ID_CUOTA NUMBER(12,0) PRIMARY KEY,
    ID_PRESTAMO NUMBER(12,0) NOT NULL REFERENCES PRESTAMO(ID_PRESTAMO),
    NUMERO_CUOTA NUMBER(6,0) NOT NULL,
    MONTO_DE_CUOTA NUMBER(15,2) NOT NULL CHECK (MONTO_DE_CUOTA > 0),
    CAPITAL_CUOTA NUMBER(15,2) NOT NULL CHECK (CAPITAL_CUOTA > 0),
    FECHA_DE_VENCIMIENTO_CUOTA TIMESTAMP,
    FECHA_DE_PAGO_CUOTA TIMESTAMP,
    ESTADO_CUOTA VARCHAR2(10 BYTE) DEFAULT 'pendiente' CHECK (ESTADO_CUOTA IN ('pendiente','pagada','vencida')),
    UNIQUE(ID_PRESTAMO, NUMERO_CUOTA)
);

CREATE TABLE ABONO_EXTRAORDINARIO (
    ID_ABONO NUMBER(12,0) PRIMARY KEY,
    ID_PRESTAMO NUMBER(12,0) NOT NULL REFERENCES PRESTAMO(ID_PRESTAMO),
    ID_TRANSACCION NUMBER(12,0),
    MONTO_ABONO NUMBER(15,2) NOT NULL CHECK (MONTO_ABONO > 0),
    FECHA_ABONO TIMESTAMP DEFAULT SYSTIMESTAMP,
    TIPO_ABONO VARCHAR2(20 BYTE) CHECK (TIPO_ABONO IN ('reduccion de plazo', 'reduccion de cuota'))
);

CREATE TABLE CAJERO (
    ID_CAJERO NUMBER(12,0) PRIMARY KEY,
    ID_SUCURSAL NUMBER(12,0) NOT NULL REFERENCES SUCURSAL(ID_SUCURSAL),
    ID_ADMINISTRADOR NUMBER(12,0) NOT NULL REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR),
    DINERO_DISPONIBLE_CAJERO NUMBER(15,2) DEFAULT 0 CHECK (DINERO_DISPONIBLE_CAJERO >= 0),
    ESTADO_CAJERO VARCHAR2(20 BYTE) DEFAULT 'activo' CHECK (ESTADO_CAJERO IN ('activo','inactivo')),
    FECHA_ULTIMA_RECARGA_CAJERO TIMESTAMP
);

CREATE TABLE TARJETA (
    ID_TARJETA NUMBER(12,0) PRIMARY KEY,
    ID_CUENTA NUMBER(12,0) NOT NULL REFERENCES CUENTA(ID_CUENTA),
    NUMERO_TARJETA VARCHAR2(25 BYTE) UNIQUE NOT NULL,
    CVV_TARJETA VARCHAR2(3 BYTE),
    FECHA_EMISION_TARJETA TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_VENCIMIENTO_TARJETA TIMESTAMP,
    ESTADO_TARJETA VARCHAR2(10 BYTE) DEFAULT 'activa' CHECK (ESTADO_TARJETA IN ('activa','inactiva','suspendida','bloqueada'))
);

CREATE TABLE TARJETA_DEBITO (
    ID_TARJETA NUMBER(12,0) PRIMARY KEY REFERENCES TARJETA(ID_TARJETA),
    LIMITE_RETIRO_DEBITO NUMBER(15,2) DEFAULT 0 CHECK (LIMITE_RETIRO_DEBITO >= 0),
    SALDO_ACTUAL_DEBITO NUMBER(15,2) DEFAULT 0 CHECK (SALDO_ACTUAL_DEBITO >= 0)
);

CREATE TABLE TARJETA_CREDITO (
    ID_TARJETA NUMBER(12,0) PRIMARY KEY REFERENCES TARJETA(ID_TARJETA),
    TASA_INTERES_CREDITO NUMBER(5,2) DEFAULT 0,
    LIMITE_CREDITO NUMBER(15,2) DEFAULT 0 CHECK (LIMITE_CREDITO >= 0),
    CUOTA_MANEJO_CREDITO NUMBER(15,2) DEFAULT 0,
    FECHA_PAGO_CREDITO TIMESTAMP,
    FECHA_CORTE_CREDITO NUMBER(2,0)
);

CREATE TABLE TRANSACCION (
    ID_TRANSACCION NUMBER(12,0) PRIMARY KEY,
    ID_CAJERO NUMBER(12,0) REFERENCES CAJERO(ID_CAJERO),
    ID_TARJETA NUMBER(12,0) REFERENCES TARJETA(ID_TARJETA),
    ID_CUENTA_ORIGEN NUMBER(12,0) REFERENCES CUENTA(ID_CUENTA),
    ID_CUENTA_DESTINO NUMBER(12,0) REFERENCES CUENTA(ID_CUENTA),
    FECHA_TRANSACCION TIMESTAMP DEFAULT SYSTIMESTAMP,
    TIPO_TRANSACCION VARCHAR2(20 BYTE) CHECK (TIPO_TRANSACCION IN ('cuenta','cajero','transferencia','pago','abono')),
    MONTO_TRANSACCION NUMBER(15,2) NOT NULL CHECK (MONTO_TRANSACCION > 0),
    ESTADO_TRANSACCION VARCHAR2(12 BYTE) CHECK (ESTADO_TRANSACCION IN ('completada','pendiente','fallida')),
    DESCRIPCION_TRANSACCION VARCHAR2(200 BYTE)
);

CREATE TABLE AUDITORIA_CAMBIOS (
    ID_AUDITORIA NUMBER(12,0) PRIMARY KEY,
    TABLA_AFECTADA VARCHAR2(50 BYTE),
    ID_REGISTRO VARCHAR2(50 BYTE),
    CAMPO_MODIFICADO VARCHAR2(50 BYTE),
    VALOR_ANTERIOR VARCHAR2(4000 BYTE),
    VALOR_NUEVO VARCHAR2(4000 BYTE),
    TIPO_OPERACION VARCHAR2(10 BYTE) CHECK (TIPO_OPERACION IN ('INSERT','UPDATE','DELETE')),
    FECHA_CAMBIO TIMESTAMP DEFAULT SYSTIMESTAMP,
    USUARIO_ORACLE VARCHAR2(100 BYTE)
);

PROMPT Tablas creadas exitosamente

-- ============================================================
-- PARTE 4: CREAR PAQUETES (Paquetes principales del sistema)
-- ============================================================

-- PKG_ADMINISTRADOR
CREATE OR REPLACE PACKAGE PKG_ADMINISTRADOR AS
    FUNCTION function_login_admin(p_email IN VARCHAR2, p_contrasena IN VARCHAR2) RETURN NUMBER;
END PKG_ADMINISTRADOR;
/

CREATE OR REPLACE PACKAGE BODY PKG_ADMINISTRADOR AS
    FUNCTION function_login_admin(p_email IN VARCHAR2, p_contrasena IN VARCHAR2) RETURN NUMBER IS
        v_id NUMBER;
    BEGIN
        SELECT id_administrador INTO v_id
        FROM administrador
        WHERE UPPER(email_administrador) = UPPER(p_email)
          AND contrasena_administrador = p_contrasena;
        RETURN v_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN NULL;
    END function_login_admin;
END PKG_ADMINISTRADOR;
/

-- PKG_CUENTA
CREATE OR REPLACE PACKAGE PKG_CUENTA AS
    FUNCTION function_login_cuenta(p_email IN VARCHAR2, p_contrasena IN VARCHAR2) RETURN NUMBER;
    PROCEDURE procedure_cambiar_saldo(p_id_cuenta IN NUMBER, p_monto IN NUMBER);
END PKG_CUENTA;
/

CREATE OR REPLACE PACKAGE BODY PKG_CUENTA AS
    FUNCTION function_login_cuenta(p_email IN VARCHAR2, p_contrasena IN VARCHAR2) RETURN NUMBER IS
        v_id_cuenta NUMBER;
    BEGIN
        SELECT c.id_cuenta INTO v_id_cuenta
        FROM cuenta c JOIN cliente cli ON cli.id_cliente = c.id_cliente
        WHERE UPPER(cli.email_cliente) = UPPER(p_email)
          AND c.contrasena_cuenta = p_contrasena
          AND c.estado_cuenta = 'activa';
        RETURN v_id_cuenta;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN NULL;
    END function_login_cuenta;

    PROCEDURE procedure_cambiar_saldo(p_id_cuenta IN NUMBER, p_monto IN NUMBER) IS
        v_saldo NUMBER;
    BEGIN
        SELECT saldo_cuenta INTO v_saldo FROM cuenta WHERE id_cuenta = p_id_cuenta;
        IF v_saldo + p_monto < 0 THEN
            RAISE_APPLICATION_ERROR(-20005, 'El saldo no puede quedar negativo.');
        END IF;
        UPDATE cuenta
        SET saldo_cuenta = v_saldo + p_monto,
            fecha_ultima_transaccion_cuenta = SYSTIMESTAMP
        WHERE id_cuenta = p_id_cuenta;
    END procedure_cambiar_saldo;
END PKG_CUENTA;
/

-- PKG_SUCURSAL
CREATE OR REPLACE PACKAGE PKG_SUCURSAL AS
    PROCEDURE procedure_listar_sucursales(o_cursor OUT SYS_REFCURSOR);
    FUNCTION function_crear_sucursal(p_nombre IN VARCHAR2, p_direccion IN VARCHAR2, 
                                    p_telefono IN VARCHAR2, p_id_admin IN NUMBER) RETURN NUMBER;
END PKG_SUCURSAL;
/

CREATE OR REPLACE PACKAGE BODY PKG_SUCURSAL AS
    PROCEDURE procedure_listar_sucursales(o_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN o_cursor FOR
            SELECT id_sucursal, nombre_sucursal, direccion_sucursal, telefono_sucursal,
                   estado_sucursal, id_administrador FROM sucursal ORDER BY id_sucursal;
    END procedure_listar_sucursales;

    FUNCTION function_crear_sucursal(p_nombre IN VARCHAR2, p_direccion IN VARCHAR2, 
                                    p_telefono IN VARCHAR2, p_id_admin IN NUMBER) RETURN NUMBER IS
        PRAGMA AUTONOMOUS_TRANSACTION;
        v_new_id NUMBER;
    BEGIN
        SELECT NVL(MAX(id_sucursal), 0) + 1 INTO v_new_id FROM sucursal;
        INSERT INTO sucursal (id_sucursal, nombre_sucursal, direccion_sucursal, 
                            telefono_sucursal, estado_sucursal, id_administrador)
        VALUES (v_new_id, p_nombre, p_direccion, p_telefono, 'abierta', p_id_admin);
        COMMIT;
        RETURN v_new_id;
    EXCEPTION
        WHEN OTHERS THEN ROLLBACK; RAISE;
    END function_crear_sucursal;
END PKG_SUCURSAL;
/

-- PKGC_PRESTAMOS (Preview - Utilizado por otros paquetes)
CREATE OR REPLACE PACKAGE PKGC_PRESTAMOS AS
    PROCEDURE procedure_actualizar_saldo(p_id_prestamo IN NUMBER);
END PKGC_PRESTAMOS;
/

CREATE OR REPLACE PACKAGE BODY PKGC_PRESTAMOS AS
    PROCEDURE procedure_actualizar_saldo(p_id_prestamo IN NUMBER) IS
        v_monto_ini NUMBER;
        v_abonos NUMBER;
        v_cuotas NUMBER;
        v_nuevo NUMBER;
    BEGIN
        SELECT monto_prestamo INTO v_monto_ini FROM prestamo WHERE id_prestamo = p_id_prestamo;
        SELECT NVL(SUM(monto_abono), 0) INTO v_abonos FROM abono_extraordinario WHERE id_prestamo = p_id_prestamo;
        SELECT NVL(SUM(capital_cuota), 0) INTO v_cuotas FROM cuota 
        WHERE id_prestamo = p_id_prestamo AND estado_cuota = 'pagada';
        v_nuevo := v_monto_ini - (v_abonos + v_cuotas);
        IF v_nuevo < 0 THEN v_nuevo := 0; END IF;
        UPDATE prestamo SET saldo_prestamo = v_nuevo, fecha_ultimo_pago_prestamo = SYSTIMESTAMP
        WHERE id_prestamo = p_id_prestamo;
    END procedure_actualizar_saldo;
END PKGC_PRESTAMOS;
/

PROMPT Paquetes creados exitosamente

-- ============================================================
-- PARTE 5: CREAR TRIGGERS (Auditoría y Validaciones)
-- ============================================================

-- Trigger: Auditoría en CLIENTE
CREATE OR REPLACE TRIGGER TRG_CLIENTE_AUDIT_INSERT
AFTER INSERT ON CLIENTE FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CAMBIOS (ID_AUDITORIA, TABLA_AFECTADA, ID_REGISTRO, 
        CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION, USUARIO_ORACLE)
    VALUES (SEQ_AUDITORIA.NEXTVAL, 'CLIENTE', :NEW.ID_CLIENTE, 'NOMBRE', 
            NULL, :NEW.NOMBRE_CLIENTE, 'INSERT', USER);
END;
/

-- Trigger: Auditoría en CUENTA
CREATE OR REPLACE TRIGGER TRG_CUENTA_AUDIT_UPDATE
AFTER UPDATE ON CUENTA FOR EACH ROW
BEGIN
    IF :OLD.SALDO_CUENTA <> :NEW.SALDO_CUENTA THEN
        INSERT INTO AUDITORIA_CAMBIOS (ID_AUDITORIA, TABLA_AFECTADA, ID_REGISTRO, 
            CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION, USUARIO_ORACLE)
        VALUES (SEQ_AUDITORIA.NEXTVAL, 'CUENTA', TO_CHAR(:NEW.ID_CUENTA), 'SALDO_CUENTA', 
                TO_CHAR(:OLD.SALDO_CUENTA), TO_CHAR(:NEW.SALDO_CUENTA), 'UPDATE', USER);
    END IF;
END;
/

-- Trigger: Validar email único antes de insertar
CREATE OR REPLACE TRIGGER TRG_CLIENTE_BEFORE_INSERT
BEFORE INSERT ON CLIENTE FOR EACH ROW
DECLARE
    v_email_existe NUMBER;
    v_cedula_existe NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_email_existe FROM CLIENTE 
    WHERE UPPER(EMAIL_CLIENTE) = UPPER(:NEW.EMAIL_CLIENTE);
    
    IF v_email_existe > 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'El email ya existe: ' || :NEW.EMAIL_CLIENTE);
    END IF;
    
    SELECT COUNT(*) INTO v_cedula_existe FROM CLIENTE 
    WHERE CEDULA_CLIENTE = :NEW.CEDULA_CLIENTE;
    
    IF v_cedula_existe > 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'La cédula ya existe: ' || :NEW.CEDULA_CLIENTE);
    END IF;
    
    IF :NEW.FECHA_REGISTRO_CLIENTE IS NULL THEN
        :NEW.FECHA_REGISTRO_CLIENTE := SYSTIMESTAMP;
    END IF;
END;
/

-- Trigger: Auditoría en PRESTAMO
CREATE OR REPLACE TRIGGER TRG_PRESTAMO_AUDIT_INSERT
AFTER INSERT ON PRESTAMO FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CAMBIOS (ID_AUDITORIA, TABLA_AFECTADA, ID_REGISTRO, 
        CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION, USUARIO_ORACLE)
    VALUES (SEQ_AUDITORIA.NEXTVAL, 'PRESTAMO', TO_CHAR(:NEW.ID_PRESTAMO), 'ESTADO', 
            NULL, :NEW.ESTADO_PRESTAMO, 'INSERT', USER);
END;
/

-- Trigger: Auditoría en TRANSACCION
CREATE OR REPLACE TRIGGER TRG_TRANSACCION_AUDIT_INSERT
AFTER INSERT ON TRANSACCION FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CAMBIOS (ID_AUDITORIA, TABLA_AFECTADA, ID_REGISTRO, 
        CAMPO_MODIFICADO, VALOR_ANTERIOR, VALOR_NUEVO, TIPO_OPERACION, USUARIO_ORACLE)
    VALUES (SEQ_AUDITORIA.NEXTVAL, 'TRANSACCION', TO_CHAR(:NEW.ID_TRANSACCION), 'ESTADO', 
            NULL, :NEW.ESTADO_TRANSACCION, 'INSERT', USER);
END;
/

PROMPT Triggers creados exitosamente

-- ============================================================
-- PARTE 6: CREAR ÍNDICES (10+ índices optimizados)
-- ============================================================

CREATE UNIQUE INDEX PK_ADMINISTRADOR ON ADMINISTRADOR(ID_ADMINISTRADOR);
CREATE UNIQUE INDEX PK_SUCURSAL ON SUCURSAL(ID_SUCURSAL);
CREATE UNIQUE INDEX PK_CLIENTE ON CLIENTE(ID_CLIENTE);
CREATE UNIQUE INDEX UQ_CLIENTE_EMAIL ON CLIENTE(EMAIL_CLIENTE);
CREATE UNIQUE INDEX UQ_CLIENTE_CEDULA ON CLIENTE(CEDULA_CLIENTE);

CREATE UNIQUE INDEX PK_CUENTA ON CUENTA(ID_CUENTA);
CREATE INDEX IDX_CUENTA_CLIENTE ON CUENTA(ID_CLIENTE);
CREATE INDEX IDX_CUENTA_SALDO_ACTIVA ON CUENTA(CASE WHEN ESTADO_CUENTA = 'activa' THEN SALDO_CUENTA ELSE NULL END);

CREATE UNIQUE INDEX PK_PRESTAMO ON PRESTAMO(ID_PRESTAMO);
CREATE INDEX IDX_PRESTAMO_CUENTA ON PRESTAMO(ID_CUENTA);
CREATE INDEX IDX_PRESTAMO_ESTADO ON PRESTAMO(ESTADO_PRESTAMO);

CREATE UNIQUE INDEX PK_CUOTA ON CUOTA(ID_CUOTA);
CREATE UNIQUE INDEX UQ_CUOTA_PRESTAMO ON CUOTA(ID_PRESTAMO, NUMERO_CUOTA);

CREATE UNIQUE INDEX PK_ABONO ON ABONO_EXTRAORDINARIO(ID_ABONO);

CREATE UNIQUE INDEX PK_CAJERO ON CAJERO(ID_CAJERO);
CREATE INDEX IDX_CAJERO_SUCURSAL ON CAJERO(ID_SUCURSAL);

CREATE UNIQUE INDEX PK_TARJETA ON TARJETA(ID_TARJETA);
CREATE UNIQUE INDEX UQ_TARJETA_NUMERO ON TARJETA(NUMERO_TARJETA);
CREATE INDEX IDX_TARJETA_CUENTA ON TARJETA(ID_CUENTA);
CREATE INDEX IDX_TARJETA_ACTIVA_CUENTA ON TARJETA(CASE WHEN ESTADO_TARJETA = 'activa' THEN ID_CUENTA ELSE NULL END);

CREATE UNIQUE INDEX PK_TARJETA_DEBITO ON TARJETA_DEBITO(ID_TARJETA);
CREATE UNIQUE INDEX PK_TARJETA_CREDITO ON TARJETA_CREDITO(ID_TARJETA);

CREATE UNIQUE INDEX PK_TRANSACCION ON TRANSACCION(ID_TRANSACCION);
CREATE INDEX IDX_TRANSACCION_FECHA ON TRANSACCION(FECHA_TRANSACCION);
CREATE INDEX IDX_TRANSACCION_ESTADO ON TRANSACCION(ESTADO_TRANSACCION);
CREATE INDEX IDX_TRANSACCION_MONTO_COMPLETADA ON TRANSACCION(CASE WHEN ESTADO_TRANSACCION = 'completada' THEN MONTO_TRANSACCION ELSE NULL END);

PROMPT Índices creados exitosamente

-- ============================================================
-- PARTE 7: INSERTAR DATOS DE PRUEBA COHERENTES
-- ============================================================

-- Administradores
INSERT INTO ADMINISTRADOR (ID_ADMINISTRADOR, EMAIL_ADMINISTRADOR, CONTRASENA_ADMINISTRADOR) 
VALUES (1, 'admin1@banco.com', 'admin123');
INSERT INTO ADMINISTRADOR (ID_ADMINISTRADOR, EMAIL_ADMINISTRADOR, CONTRASENA_ADMINISTRADOR) 
VALUES (2, 'admin2@banco.com', 'admin456');

-- Sucursales
INSERT INTO SUCURSAL (ID_SUCURSAL, NOMBRE_SUCURSAL, DIRECCION_SUCURSAL, TELEFONO_SUCURSAL, ESTADO_SUCURSAL, ID_ADMINISTRADOR) 
VALUES (1, 'Sucursal Centro', 'Calle 50 # 10-20, Bogotá', '6012345678', 'abierta', 1);
INSERT INTO SUCURSAL (ID_SUCURSAL, NOMBRE_SUCURSAL, DIRECCION_SUCURSAL, TELEFONO_SUCURSAL, ESTADO_SUCURSAL, ID_ADMINISTRADOR) 
VALUES (2, 'Sucursal Norte', 'Avenida 68 # 5-30, Bogotá', '6012345679', 'abierta', 1);
INSERT INTO SUCURSAL (ID_SUCURSAL, NOMBRE_SUCURSAL, DIRECCION_SUCURSAL, TELEFONO_SUCURSAL, ESTADO_SUCURSAL, ID_ADMINISTRADOR) 
VALUES (3, 'Sucursal Sur', 'Carrera 30 # 15-45, Bogotá', '6012345680', 'abierta', 2);

-- Clientes
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, EMAIL_CLIENTE, TELEFONO_CLIENTE, CEDULA_CLIENTE, ESTADO_CLIENTE) 
VALUES ('CLI001', 'Juan Pérez García', 'juan.perez@email.com', '3001234567', 1234567890, 'ACTIVO');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, EMAIL_CLIENTE, TELEFONO_CLIENTE, CEDULA_CLIENTE, ESTADO_CLIENTE) 
VALUES ('CLI002', 'María López Martínez', 'maria.lopez@email.com', '3002345678', 2345678901, 'ACTIVO');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, EMAIL_CLIENTE, TELEFONO_CLIENTE, CEDULA_CLIENTE, ESTADO_CLIENTE) 
VALUES ('CLI003', 'Carlos Rodríguez Sánchez', 'carlos.rodriguez@email.com', '3003456789', 3456789012, 'ACTIVO');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, EMAIL_CLIENTE, TELEFONO_CLIENTE, CEDULA_CLIENTE, ESTADO_CLIENTE) 
VALUES ('CLI004', 'Ana Gómez Torres', 'ana.gomez@email.com', '3004567890', 4567890123, 'ACTIVO');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, EMAIL_CLIENTE, TELEFONO_CLIENTE, CEDULA_CLIENTE, ESTADO_CLIENTE) 
VALUES ('CLI005', 'Luis Fernández Díaz', 'luis.fernandez@email.com', '3005678901', 5678901234, 'ACTIVO');

-- Cuentas
INSERT INTO CUENTA (ID_CUENTA, ID_CLIENTE, ID_ADMINISTRADOR, SALDO_CUENTA, ESTADO_CUENTA, CONTRASENA_CUENTA) 
VALUES (1, 'CLI001', 1, 5000000, 'activa', '1234567890');
INSERT INTO CUENTA (ID_CUENTA, ID_CLIENTE, ID_ADMINISTRADOR, SALDO_CUENTA, ESTADO_CUENTA, CONTRASENA_CUENTA) 
VALUES (2, 'CLI002', 1, 3000000, 'activa', '2345678901');
INSERT INTO CUENTA (ID_CUENTA, ID_CLIENTE, ID_ADMINISTRADOR, SALDO_CUENTA, ESTADO_CUENTA, CONTRASENA_CUENTA) 
VALUES (3, 'CLI003', 2, 7500000, 'activa', '3456789012');
INSERT INTO CUENTA (ID_CUENTA, ID_CLIENTE, ID_ADMINISTRADOR, SALDO_CUENTA, ESTADO_CUENTA, CONTRASENA_CUENTA) 
VALUES (4, 'CLI004', 1, 2000000, 'activa', '4567890123');
INSERT INTO CUENTA (ID_CUENTA, ID_CLIENTE, ID_ADMINISTRADOR, SALDO_CUENTA, ESTADO_CUENTA, CONTRASENA_CUENTA) 
VALUES (5, 'CLI005', 2, 1000000, 'activa', '5678901234');

-- Cajeros
INSERT INTO CAJERO (ID_CAJERO, ID_SUCURSAL, ID_ADMINISTRADOR, DINERO_DISPONIBLE_CAJERO, ESTADO_CAJERO) 
VALUES (1, 1, 1, 50000000, 'activo');
INSERT INTO CAJERO (ID_CAJERO, ID_SUCURSAL, ID_ADMINISTRADOR, DINERO_DISPONIBLE_CAJERO, ESTADO_CAJERO) 
VALUES (2, 1, 1, 30000000, 'activo');
INSERT INTO CAJERO (ID_CAJERO, ID_SUCURSAL, ID_ADMINISTRADOR, DINERO_DISPONIBLE_CAJERO, ESTADO_CAJERO) 
VALUES (3, 2, 1, 40000000, 'activo');
INSERT INTO CAJERO (ID_CAJERO, ID_SUCURSAL, ID_ADMINISTRADOR, DINERO_DISPONIBLE_CAJERO, ESTADO_CAJERO) 
VALUES (4, 3, 2, 35000000, 'activo');

-- Préstamos
INSERT INTO PRESTAMO (ID_PRESTAMO, ID_SUCURSAL, MONTO_PRESTAMO, TASA_DE_INTERES_PRESTAMO, PLAZO_PRESTAMO, 
    FECHA_INICIO_PRESTAMO, FECHA_VENCIMIENTO_PRESTAMO, ESTADO_PRESTAMO, SALDO_PRESTAMO, ID_CUENTA) 
VALUES (1, 1, 10000000, 1.5, 12, SYSTIMESTAMP, ADD_MONTHS(SYSTIMESTAMP, 12), 'activo', 10000000, 1);
INSERT INTO PRESTAMO (ID_PRESTAMO, ID_SUCURSAL, MONTO_PRESTAMO, TASA_DE_INTERES_PRESTAMO, PLAZO_PRESTAMO, 
    FECHA_INICIO_PRESTAMO, FECHA_VENCIMIENTO_PRESTAMO, ESTADO_PRESTAMO, SALDO_PRESTAMO, ID_CUENTA) 
VALUES (2, 2, 5000000, 1.5, 6, SYSTIMESTAMP, ADD_MONTHS(SYSTIMESTAMP, 6), 'activo', 5000000, 2);
INSERT INTO PRESTAMO (ID_PRESTAMO, ID_SUCURSAL, MONTO_PRESTAMO, TASA_DE_INTERES_PRESTAMO, PLAZO_PRESTAMO, 
    FECHA_INICIO_PRESTAMO, FECHA_VENCIMIENTO_PRESTAMO, ESTADO_PRESTAMO, SALDO_PRESTAMO, ID_CUENTA) 
VALUES (3, 1, 15000000, 1.5, 0, SYSTIMESTAMP, NULL, 'solicitado', 15000000, 3);

-- Cuotas (Préstamo 1: 12 cuotas)
INSERT INTO CUOTA (ID_CUOTA, ID_PRESTAMO, NUMERO_CUOTA, MONTO_DE_CUOTA, CAPITAL_CUOTA, 
    FECHA_DE_VENCIMIENTO_CUOTA, ESTADO_CUOTA) 
VALUES (1, 1, 1, 875000, 833333.33, ADD_MONTHS(SYSTIMESTAMP, 1), 'pendiente');
INSERT INTO CUOTA (ID_CUOTA, ID_PRESTAMO, NUMERO_CUOTA, MONTO_DE_CUOTA, CAPITAL_CUOTA, 
    FECHA_DE_VENCIMIENTO_CUOTA, ESTADO_CUOTA) 
VALUES (2, 1, 2, 875000, 833333.33, ADD_MONTHS(SYSTIMESTAMP, 2), 'pendiente');
INSERT INTO CUOTA (ID_CUOTA, ID_PRESTAMO, NUMERO_CUOTA, MONTO_DE_CUOTA, CAPITAL_CUOTA, 
    FECHA_DE_VENCIMIENTO_CUOTA, ESTADO_CUOTA) 
VALUES (3, 1, 3, 875000, 833333.33, ADD_MONTHS(SYSTIMESTAMP, 3), 'pendiente');

-- Cuotas (Préstamo 2: 6 cuotas)
INSERT INTO CUOTA (ID_CUOTA, ID_PRESTAMO, NUMERO_CUOTA, MONTO_DE_CUOTA, CAPITAL_CUOTA, 
    FECHA_DE_VENCIMIENTO_CUOTA, ESTADO_CUOTA) 
VALUES (4, 2, 1, 875000, 833333.33, ADD_MONTHS(SYSTIMESTAMP, 1), 'pendiente');
INSERT INTO CUOTA (ID_CUOTA, ID_PRESTAMO, NUMERO_CUOTA, MONTO_DE_CUOTA, CAPITAL_CUOTA, 
    FECHA_DE_VENCIMIENTO_CUOTA, ESTADO_CUOTA) 
VALUES (5, 2, 2, 875000, 833333.33, ADD_MONTHS(SYSTIMESTAMP, 2), 'pendiente');

-- Tarjetas de Débito
INSERT INTO TARJETA (ID_TARJETA, ID_CUENTA, NUMERO_TARJETA, CVV_TARJETA, 
    FECHA_EMISION_TARJETA, FECHA_VENCIMIENTO_TARJETA, ESTADO_TARJETA) 
VALUES (1, 1, '4111111111111111', '123', SYSTIMESTAMP, ADD_MONTHS(SYSTIMESTAMP, 48), 'activa');
INSERT INTO TARJETA_DEBITO (ID_TARJETA, LIMITE_RETIRO_DEBITO, SALDO_ACTUAL_DEBITO) 
VALUES (1, 2000000, 0);

INSERT INTO TARJETA (ID_TARJETA, ID_CUENTA, NUMERO_TARJETA, CVV_TARJETA, 
    FECHA_EMISION_TARJETA, FECHA_VENCIMIENTO_TARJETA, ESTADO_TARJETA) 
VALUES (2, 2, '5222222222222222', '456', SYSTIMESTAMP, ADD_MONTHS(SYSTIMESTAMP, 48), 'activa');
INSERT INTO TARJETA_DEBITO (ID_TARJETA, LIMITE_RETIRO_DEBITO, SALDO_ACTUAL_DEBITO) 
VALUES (2, 1500000, 0);

-- Tarjetas de Crédito
INSERT INTO TARJETA (ID_TARJETA, ID_CUENTA, NUMERO_TARJETA, CVV_TARJETA, 
    FECHA_EMISION_TARJETA, FECHA_VENCIMIENTO_TARJETA, ESTADO_TARJETA) 
VALUES (3, 1, '3333333333333333', '789', SYSTIMESTAMP, ADD_MONTHS(SYSTIMESTAMP, 48), 'activa');
INSERT INTO TARJETA_CREDITO (ID_TARJETA, TASA_INTERES_CREDITO, LIMITE_CREDITO, 
    CUOTA_MANEJO_CREDITO, FECHA_PAGO_CREDITO, FECHA_CORTE_CREDITO) 
VALUES (3, 2.5, 5000000, 15000, SYSTIMESTAMP, 15);

INSERT INTO TARJETA (ID_TARJETA, ID_CUENTA, NUMERO_TARJETA, CVV_TARJETA, 
    FECHA_EMISION_TARJETA, FECHA_VENCIMIENTO_TARJETA, ESTADO_TARJETA) 
VALUES (4, 3, '3434343434343434', '321', SYSTIMESTAMP, ADD_MONTHS(SYSTIMESTAMP, 48), 'activa');
INSERT INTO TARJETA_CREDITO (ID_TARJETA, TASA_INTERES_CREDITO, LIMITE_CREDITO, 
    CUOTA_MANEJO_CREDITO, FECHA_PAGO_CREDITO, FECHA_CORTE_CREDITO) 
VALUES (4, 2.5, 7500000, 18000, SYSTIMESTAMP, 20);

-- Transacciones de Ejemplo
INSERT INTO TRANSACCION (ID_TRANSACCION, ID_CUENTA_ORIGEN, ID_CUENTA_DESTINO, MONTO_TRANSACCION, 
    TIPO_TRANSACCION, ESTADO_TRANSACCION, DESCRIPCION_TRANSACCION) 
VALUES (1, 1, 2, 500000, 'transferencia', 'completada', 'Transferencia entre cuentas');
INSERT INTO TRANSACCION (ID_TRANSACCION, ID_CAJERO, ID_TARJETA, MONTO_TRANSACCION, 
    TIPO_TRANSACCION, ESTADO_TRANSACCION, DESCRIPCION_TRANSACCION) 
VALUES (2, 1, 1, 200000, 'cajero', 'completada', 'Retiro en cajero automático');
INSERT INTO TRANSACCION (ID_TRANSACCION, ID_CAJERO, ID_TARJETA, MONTO_TRANSACCION, 
    TIPO_TRANSACCION, ESTADO_TRANSACCION, DESCRIPCION_TRANSACCION) 
VALUES (3, 1, 3, 150000, 'cajero', 'completada', 'Retiro con tarjeta de crédito');

COMMIT;

PROMPT Datos de prueba insertados exitosamente

-- ============================================================
-- PARTE 8: VERIFICACIÓN FINAL
-- ============================================================

SET FEEDBACK ON

PROMPT ============================================================
PROMPT SCRIPT MAESTRO COMPLETADO EXITOSAMENTE
PROMPT ============================================================
PROMPT Resumen de Objetos Creados:
PROMPT - Secuencias: 10
PROMPT - Tablas: 11 (incluyendo AUDITORIA_CAMBIOS)
PROMPT - Paquetes: 5 (PKG_ADMINISTRADOR, PKG_CUENTA, PKG_SUCURSAL, PKGC_PRESTAMOS)
PROMPT - Triggers: 6 (Auditoría y Validaciones)
PROMPT - Índices: 25+ (Optimización de consultas)
PROMPT - Registros de Prueba: 40+
PROMPT ============================================================

-- Verificar carga de datos
PROMPT
PROMPT Verificación de datos cargados:

SELECT 'ADMINISTRADORES' AS TABLA, COUNT(*) AS CANTIDAD FROM ADMINISTRADOR
UNION ALL
SELECT 'SUCURSALES', COUNT(*) FROM SUCURSAL
UNION ALL
SELECT 'CLIENTES', COUNT(*) FROM CLIENTE
UNION ALL
SELECT 'CUENTAS', COUNT(*) FROM CUENTA
UNION ALL
SELECT 'PRESTAMOS', COUNT(*) FROM PRESTAMO
UNION ALL
SELECT 'CUOTAS', COUNT(*) FROM CUOTA
UNION ALL
SELECT 'CAJEROS', COUNT(*) FROM CAJERO
UNION ALL
SELECT 'TARJETAS', COUNT(*) FROM TARJETA
UNION ALL
SELECT 'TRANSACCIONES', COUNT(*) FROM TRANSACCION
ORDER BY TABLA;

PROMPT
PROMPT ============================================================
PROMPT FIN DE LA EJECUCIÓN
PROMPT ============================================================
